"""empty message

Revision ID: 269bbc9c7156
Revises: 
Create Date: 2023-02-20 16:10:23.984498

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '269bbc9c7156'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ordered_products', sa.PickleType(), nullable=True))
        batch_op.drop_constraint('orders_product_id_fkey', type_='foreignkey')
        batch_op.drop_column('products')
        batch_op.drop_column('product_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('products', postgresql.BYTEA(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('orders_product_id_fkey', 'products', ['product_id'], ['id'])
        batch_op.drop_column('ordered_products')

    # ### end Alembic commands ###
