"""empty message

Revision ID: d1438afa966e
Revises: 269bbc9c7156
Create Date: 2023-02-20 23:15:31.964569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1438afa966e'
down_revision = '269bbc9c7156'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_product')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_product',
    sa.Column('order_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='order_product_order_id_fkey'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='order_product_product_id_fkey'),
    sa.PrimaryKeyConstraint('order_id', 'product_id', name='order_product_pkey')
    )
    # ### end Alembic commands ###
