"""empty message

Revision ID: 155cb46f90ba
Revises: 2156f7f9272d
Create Date: 2022-08-24 23:53:42.651720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '155cb46f90ba'
down_revision = '2156f7f9272d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'admin',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'admin',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
