"""update user admin

Revision ID: 1c1b1d3d6924
Revises: ce11bfb6cbfe
Create Date: 2022-08-21 21:16:40.758317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c1b1d3d6924'
down_revision = 'ce11bfb6cbfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('userAdmin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'userAdmin')
    # ### end Alembic commands ###
