"""update user 3

Revision ID: 2156f7f9272d
Revises: 1c1b1d3d6924
Create Date: 2022-08-21 21:20:03.784930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2156f7f9272d'
down_revision = '1c1b1d3d6924'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('admin', sa.Boolean(), nullable=True))
    op.drop_column('users', 'userAdmin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('userAdmin', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('users', 'admin')
    # ### end Alembic commands ###
