"""empty message

Revision ID: 4e6bd8f3a31e
Revises: c75838475dbb
Create Date: 2022-10-19 14:30:33.239222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e6bd8f3a31e'
down_revision = 'c75838475dbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message_notification', sa.Column('sender', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message_notification', 'sender')
    # ### end Alembic commands ###
