"""update ratings table(3)

Revision ID: 50c565b13a1a
Revises: d0130f64d039
Create Date: 2022-09-01 21:18:46.893950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50c565b13a1a'
down_revision = 'd0130f64d039'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ratings', sa.Column('userCountryCode', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ratings', 'userCountryCode')
    # ### end Alembic commands ###
