"""Initial migration.

Revision ID: 5ac38824eabf
Revises: 
Create Date: 2022-07-04 12:38:36.648582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ac38824eabf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessions')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('state',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('zipcode',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('products',
               existing_type=sa.BLOB(),
               nullable=True)
        batch_op.drop_column('countery')
        batch_op.drop_column('address')
        batch_op.drop_column('fullname')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fullname', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('address', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('countery', sa.VARCHAR(), nullable=False))
        batch_op.alter_column('products',
               existing_type=sa.BLOB(),
               nullable=False)
        batch_op.alter_column('zipcode',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('state',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(),
               nullable=False)

    op.create_table('sessions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('data', sa.BLOB(), nullable=True),
    sa.Column('expiry', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    # ### end Alembic commands ###
