"""empty message

Revision ID: 76e832b3b251
Revises: d1438afa966e
Create Date: 2023-02-21 20:24:30.260718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76e832b3b251'
down_revision = 'd1438afa966e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deliveryTime', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('deliveryTime')

    # ### end Alembic commands ###
