"""update orders tabel

Revision ID: 8be82ad19547
Revises: 155cb46f90ba
Create Date: 2022-08-24 23:57:57.849316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8be82ad19547'
down_revision = '155cb46f90ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('paymentMethod', sa.PickleType(), nullable=True))
    op.add_column('orders', sa.Column('deliveryStatus', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('trackingNumber', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'trackingNumber')
    op.drop_column('orders', 'deliveryStatus')
    op.drop_column('orders', 'paymentMethod')
    # ### end Alembic commands ###
