"""empty message

Revision ID: 9780878f71db
Revises: c2a3a67ff955
Create Date: 2022-10-18 20:14:31.093753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9780878f71db'
down_revision = 'c2a3a67ff955'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'message_notification', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'message_notification', type_='unique')
    # ### end Alembic commands ###
