"""update globalCoupon table

Revision ID: 9ea49eabd3da
Revises: c696275c141a
Create Date: 2022-09-04 19:35:39.301812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ea49eabd3da'
down_revision = 'c696275c141a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('global_coupon', 'product_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_unique_constraint(None, 'global_coupon', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'global_coupon', type_='unique')
    op.alter_column('global_coupon', 'product_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
