"""empty message

Revision ID: acb9e1410928
Revises: 9780878f71db
Create Date: 2022-10-18 20:28:54.300125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acb9e1410928'
down_revision = '9780878f71db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message_notification', sa.Column('user_id', sa.String(), nullable=False))
    op.add_column('message_notification', sa.Column('room_id', sa.String(), nullable=False))
    op.create_foreign_key(None, 'message_notification', 'rooms', ['room_id'], ['id'])
    op.create_foreign_key(None, 'message_notification', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'message_notification', type_='foreignkey')
    op.drop_constraint(None, 'message_notification', type_='foreignkey')
    op.drop_column('message_notification', 'room_id')
    op.drop_column('message_notification', 'user_id')
    # ### end Alembic commands ###
