"""add globalCoupon table and add relationship between globalCoupon and products

Revision ID: c696275c141a
Revises: 50c565b13a1a
Create Date: 2022-09-04 19:33:52.823722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c696275c141a'
down_revision = '50c565b13a1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_coupon',
    sa.Column('id', sa.String(length=35), nullable=False),
    sa.Column('globalCuppon', sa.String(length=30), nullable=True),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.add_column('products', sa.Column('coupon', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'ratings', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ratings', type_='unique')
    op.drop_column('products', 'coupon')
    op.drop_table('global_coupon')
    # ### end Alembic commands ###
