"""empty message

Revision ID: c75838475dbb
Revises: acb9e1410928
Create Date: 2022-10-19 14:26:33.396504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c75838475dbb'
down_revision = 'acb9e1410928'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message_notification', sa.Column('receiver_id', sa.String(), nullable=False))
    op.drop_constraint('message_notification_user_id_fkey', 'message_notification', type_='foreignkey')
    op.create_foreign_key(None, 'message_notification', 'users', ['receiver_id'], ['id'])
    op.drop_column('message_notification', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message_notification', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'message_notification', type_='foreignkey')
    op.create_foreign_key('message_notification_user_id_fkey', 'message_notification', 'users', ['user_id'], ['id'])
    op.drop_column('message_notification', 'receiver_id')
    # ### end Alembic commands ###
