"""update user.

Revision ID: ce11bfb6cbfe
Revises: 
Create Date: 2022-08-20 15:13:59.486025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce11bfb6cbfe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('gender', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'products', ['id'])
    op.create_unique_constraint(None, 'ratings', ['id'])
    op.add_column('users', sa.Column('country', sa.String(length=30), nullable=False))
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'country')
    op.drop_constraint(None, 'ratings', type_='unique')
    op.drop_constraint(None, 'products', type_='unique')
    op.drop_column('products', 'gender')
    # ### end Alembic commands ###
