"""update ratings table

Revision ID: d0130f64d039
Revises: 6d3acd878d84
Create Date: 2022-09-01 20:27:35.485432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0130f64d039'
down_revision = '6d3acd878d84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ratings', sa.Column('rateDate', sa.DateTime(), nullable=True))
    op.add_column('ratings', sa.Column('userName', sa.String(), nullable=True))
    op.add_column('ratings', sa.Column('userCountry', sa.String(), nullable=True))
    op.drop_constraint('ratings_user_id_fkey', 'ratings', type_='foreignkey')
    op.drop_column('ratings', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ratings', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key('ratings_user_id_fkey', 'ratings', 'users', ['user_id'], ['id'])
    op.drop_column('ratings', 'userCountry')
    op.drop_column('ratings', 'userName')
    op.drop_column('ratings', 'rateDate')
    # ### end Alembic commands ###
