"""empty message

Revision ID: d81e54db949c
Revises: 
Create Date: 2023-01-17 18:01:22.431736

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd81e54db949c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message_notification')
    op.create_unique_constraint(None, 'display', ['id'])
    op.create_unique_constraint(None, 'global_coupon', ['id'])
    op.create_unique_constraint(None, 'orders', ['id'])
    op.create_unique_constraint(None, 'products', ['id'])
    op.create_unique_constraint(None, 'ratings', ['id'])
    op.create_unique_constraint(None, 'rooms', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'rooms', type_='unique')
    op.drop_constraint(None, 'ratings', type_='unique')
    op.drop_constraint(None, 'products', type_='unique')
    op.drop_constraint(None, 'orders', type_='unique')
    op.drop_constraint(None, 'global_coupon', type_='unique')
    op.drop_constraint(None, 'display', type_='unique')
    op.create_table('message_notification',
    sa.Column('id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('notification', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('notify_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('receiver_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('sender', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('room_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], name='message_notification_receiver_id_fkey'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name='message_notification_room_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='message_notification_pkey')
    )
    # ### end Alembic commands ###
