"""empty message

Revision ID: dd39b029b489
Revises: d81e54db949c
Create Date: 2023-01-28 15:12:23.349681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd39b029b489'
down_revision = 'd81e54db949c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reset_token', sa.String(length=36), nullable=True))
    op.add_column('users', sa.Column('token_expiration', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'token_expiration')
    op.drop_column('users', 'reset_token')
    # ### end Alembic commands ###
