"""update products table

Revision ID: fa49bb3d6553
Revises: 4e6bd8f3a31e
Create Date: 2022-11-17 18:11:40.609793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa49bb3d6553'
down_revision = '4e6bd8f3a31e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('series', sa.Text(), nullable=True))
    op.drop_column('products', 'gender')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('gender', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('products', 'series')
    # ### end Alembic commands ###
